In [1]:
import numpy as np
unique = []
train_file = open('pos_train.txt','r')
text = train_file.read()
words = text.split()
for word in words:
    if word not in unique:
        unique.append(word)
train_file.close()
train_file2 = open('pos_train.txt','r')
print(unique)
print(len(unique))


['<s>', 'ADP', 'DET', 'NOUN', 'VERB', 'ADJ', 'CONJ', 'PRT', '.', 'ADV', 'NUM', 'PRON', 'X']
13


In [2]:
words

['<s>',
 'ADP',
 'DET',
 'NOUN',
 'NOUN',
 'NOUN',
 'VERB',
 'ADJ',
 'CONJ',
 'ADJ',
 'NOUN',
 'PRT',
 'VERB',
 'DET',
 'NOUN',
 '.',
 '<s>',
 'VERB',
 'ADJ',
 'NOUN',
 'VERB',
 'DET',
 'ADJ',
 'NOUN',
 'ADP',
 'ADJ',
 'NOUN',
 '.',
 'CONJ',
 'DET',
 'NOUN',
 'ADP',
 'VERB',
 'NOUN',
 'NOUN',
 'VERB',
 'VERB',
 'ADV',
 'ADJ',
 '.',
 '<s>',
 'ADP',
 'DET',
 'NOUN',
 'VERB',
 'VERB',
 '.',
 'DET',
 'NOUN',
 'ADP',
 'ADJ',
 'NOUN',
 'VERB',
 'ADV',
 '.',
 '<s>',
 'CONJ',
 'NOUN',
 'ADJ',
 'ADP',
 'NOUN',
 'NOUN',
 'VERB',
 'ADP',
 'DET',
 'NOUN',
 '.',
 '<s>',
 'NOUN',
 'NUM',
 'ADV',
 'ADV',
 'VERB',
 'DET',
 'NOUN',
 'ADP',
 'NOUN',
 'ADP',
 'NOUN',
 'CONJ',
 'NOUN',
 '.',
 '<s>',
 'DET',
 'NOUN',
 'ADP',
 'NOUN',
 'VERB',
 'ADV',
 'VERB',
 'NOUN',
 'ADP',
 'PRON',
 '.',
 '<s>',
 'PRON',
 'VERB',
 'ADV',
 'VERB',
 'ADJ',
 'NOUN',
 '.',
 'ADJ',
 'NOUN',
 'CONJ',
 'ADJ',
 'NOUN',
 '.',
 '<s>',
 'CONJ',
 'PRON',
 'VERB',
 'VERB',
 'ADP',
 'NOUN',
 'VERB',
 'VERB',
 'ADV',
 'ADP',
 'DET',
 

**Transition Probablity Matrix**

In [3]:
dictionary_pos = {}   #dictionary for storing all POS and assigning unique serial for each
for i in range(len(unique)):
    dictionary_pos[i] = unique[i]
print(dictionary_pos)
transition_matrix = [[0]*13 for i in range(13)]  #transition matrix size is 13 as number of tags is 13
temp = 0
while temp!=1:
    x=train_file2.readline()
    if len(x)>0:
        wordlist = x.split(' ')
        for i in range(len(wordlist)-1):
            for j in range((len(dictionary_pos))):
                if(wordlist[i]==dictionary_pos.get(j)):
                    x_transition_matrix = j              #coordinate for x axis of transition matrix
                elif(wordlist[i+1]==dictionary_pos.get(j)):
                    y_transition_matrix = j              #coordinate for y axis of transition matrix
            transition_matrix[x_transition_matrix][y_transition_matrix]+=1  #incrementing for occurence of each pos for the set sequence
    else:
        temp = 1
transition_matrix_array = np.array(transition_matrix) 
print(transition_matrix_array)
print(transition_matrix_array.sum(axis =1)[:,None])
transition_matrix_array = transition_matrix_array/transition_matrix_array.sum(axis=1)[:,None] #this step is for calculating probablities for each transition
print(transition_matrix_array)
train_file2.close()

{0: '<s>', 1: 'ADP', 2: 'DET', 3: 'NOUN', 4: 'VERB', 5: 'ADJ', 6: 'CONJ', 7: 'PRT', 8: '.', 9: 'ADV', 10: 'NUM', 11: 'PRON', 12: 'X'}
[[    0  2557  4651  2891   819   652   707   906  2418  2044   393  3952
     10]
 [    0  1100 26219 13711  2381  4629   124   865   438   926  1724  4073
     24]
 [    0   492   297 33991  3703 11886    31   119   571   845   534   479
     80]
 [    0 25775  1660 14154 17668  1257  6150  1826 28817  2828  1068  1791
     39]
 [    0 12459 11100  6916 13647  4124  1084  4917  6117  7595   551  4304
     11]
 [    0  2815   182 20075   576  1758  1162   587  3148   341   183   126
      7]
 [    0  1087  2061  3342  3077  1548     3   378   311  1292   344   998
      6]
 [    0  1214   967   395  7290   242   172   156  1077   512    55    94
      0]
 [    0  3615  3911  4436  4304  1520  4108  1217 27170  2698   861  2788
     60]
 [    0  3219  1522   670  5174  2817   415   646  4382  2073   312  1092
      1]
 [    0   811    85  2233   288   32

In [4]:
unique_words_tokens = []     
train_tokens_file = open('tokens_train.txt','r')
tokens_text = train_tokens_file.read()
tokens = tokens_text.split()
for token in tokens:
    if token not in unique_words_tokens:
        unique_words_tokens.append(token)
print(len(unique_words_tokens))     #number of unique words or tokens


29936


**VOCABULARY FOR ALL THE TAGS**

In [ ]:
vocab={}    #dictionary for vocabulary of tags
temp2=0

train_tokens_file.seek(0)
for i in range(22000):
    x2=train_tokens_file.readline().split(' ')
    for word in x2:
        if word not in vocab:
            vocab[word]=1
        else:
            vocab[word]+=1
            
print(vocab)


In [6]:
train_tokens_file.close()

In [7]:
len(unique_words_tokens)

29936

In [ ]:
dictionary_token = {}
for i in range(len(unique_words_tokens)):
    dictionary_token[i] = unique_words_tokens[i]
print(dictionary_token)

In [9]:
reversed_dictionary_pos = {value : key for (key, value) in dictionary_pos.items()} #reversing the pos dictionary
print(reversed_dictionary_pos)

{'<s>': 0, 'ADP': 1, 'DET': 2, 'NOUN': 3, 'VERB': 4, 'ADJ': 5, 'CONJ': 6, 'PRT': 7, '.': 8, 'ADV': 9, 'NUM': 10, 'PRON': 11, 'X': 12}


In [ ]:
reversed_dictionary_token = {value : key for (key, value) in dictionary_token.items()} #reversing the tag dictionary
print(reversed_dictionary_token)

In [ ]:
emission_matrix = [[0]*29936 for i in range(13)] 
x_emission_file = open('pos_train.txt')
y_emission_file = open('tokens_train.txt')
temp = 0
x = x_emission_file.read()
y = y_emission_file.read()
wordlist_x = x.split()
wordlist_y = y.split()
for i in range(len(wordlist_x)):
    x_emission_matrix = reversed_dictionary_pos.get(wordlist_x[i])
    y_emission_matrix = reversed_dictionary_token.get(wordlist_y[i])
    emission_matrix[x_emission_matrix][y_emission_matrix]+=1 #incrementing the sequence of emissions in the particular position in the list
print(emission_matrix[3])
print(i)


In [12]:
emission_matrix_array = np.array(emission_matrix)
print(emission_matrix_array)

[[22000     0     0 ...     0     0     0]
 [    0   157  2357 ...     0     0     0]
 [    0     0   805 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0   561 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]


In [13]:
countt = 0
for i in range(13):
    for j in range(29935):
        if(emission_matrix_array[i][j]>0):
            countt+=1
print(countt)

31921


**Emission Probablity Matrix**

In [14]:
emission_matrix_array = emission_matrix_array/emission_matrix_array.sum(axis=1)[:,None] #division for emission probablity 
print(emission_matrix_array)

[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.0027929  0.04192906 ... 0.         0.         0.        ]
 [0.         0.         0.01518066 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.02823068 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [15]:
x_emission_file.close()
y_emission_file.close()

**Viterbi Algorithm**

In [16]:
test_pos_file2 = open('pos_test.text','r')
test_token_file2 = open('tokens_test.txt','r')
len_found_sentences = 0
temp = 0
correct_prediction = 0
word_not_found = 0
while(temp!=1):  #while there is a sentence
    test_pos2 = test_pos_file2.readline()
    test_token2 = test_token_file2.readline()
    if len(test_pos2)>0:
        words_test_token2 = test_token2.split()
        words_test_pos2 = test_pos2.split()
        words_test_token2.remove('<s>') #logic of this algo is based on the sentence without start tag
        temp_list_current = []
        temp_list_current_index = []
        temp_list_previous = ['<s>']
        temp_list_previous_index = []
        predicted_pos_list_words = []
        biggest_prob= -1
        initial_prob = 1
        predicted_pos_list = [0]  #populating it initially by start tag
        r=0
        for comp in words_test_token2:
            if comp in unique_words_tokens:
                r+=1
        if(r==len(words_test_token2)):  #if any of the words is not in the train set, it will leave execution otherwise will continue
            len_found_sentences+=1   #tag for tracking number of sentences where words found in training data
            temp_list_current = []
            temp_list_current_index = [] #list for tracking current states
            temp_list_previous = ['<s>'] #list for tracking previous states
            temp_list_previous_index = []
            predicted_pos_list_words = []
            biggest_prob= -1
            initial_prob = 1
            predicted_pos_list = [0]
            for i in range(len(words_test_token2)):
                col = reversed_dictionary_token.get(words_test_token2[i])
                temp_arr = emission_matrix_array[:,col]
                for j in range(len(temp_arr)):
                    if(temp_arr[j]>0):
                        temp_list_current.append(dictionary_pos[j])
                for m in temp_list_previous:
                    temp_list_previous_index.append(reversed_dictionary_pos.get(m)) #getting serial number for each pos (previous)
                for n in temp_list_current:
                    temp_list_current_index.append(reversed_dictionary_pos.get(n)) #getting serial number for each pos (current)
                for p in temp_list_previous_index:
                    biggest_prob = -1
                    for q in temp_list_current_index:
                        temp_prob = transition_matrix_array[p][q]*temp_arr[q]*initial_prob #multiplying all probablities
                        if(temp_prob>biggest_prob): #viterbi core concept of selecting only the largest probablity
                            biggest_prob = temp_prob
                            x_p = p
                            y_q = q
                initial_prob = biggest_prob
                predicted_pos_list.append(y_q)                
                temp_list_previous = [dictionary_pos[y_q]]          
            
            for i in predicted_pos_list:
                predicted_pos_list_words.append(dictionary_pos[i])   
            if(words_test_pos2==predicted_pos_list_words):
                correct_prediction+=1    #if predictions are correct
        elif(r!= len(words_test_token2)): #if any of the words in the sentence is not present in training data
            word_not_found+=1
    else:
        temp = 1        
        
        
    

In [17]:
print('The total correct predictions are',correct_prediction)
print('The total sentences where words are found in training data are',len_found_sentences)
print('The number of sentences whose words are not found in training data is',word_not_found)
accuracy = correct_prediction/len_found_sentences*100
print('the accuracy of Viterbi Algorithm is ',accuracy,'%')

The total correct predictions are 1549
The total sentences where words are found in training data are 2629
The number of sentences whose words are not found in training data is 2863
the accuracy of Viterbi Algorithm is  58.919741346519594 %
